// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAOEAoRKBGPxImqxgdCwxu7JXKUkAkH8I',
    appId: '1:91810779138:web:d93a7002628d94e7f8171b',
    messagingSenderId: '91810779138',
    projectId: 'running-loja',
    authDomain: 'running-loja.firebaseapp.com',
    databaseURL: 'https://running-loja-default-rtdb.firebaseio.com',
    storageBucket: 'running-loja.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi3Frz-bzw3eIaENNhxOvioVOexJqYo2E',
    appId: '1:91810779138:android:9705e5c1573398d5f8171b',
    messagingSenderId: '91810779138',
    projectId: 'running-loja',
    databaseURL: 'https://running-loja-default-rtdb.firebaseio.com',
    storageBucket: 'running-loja.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPv-InEyB1sBqS8YUGbIIXFy5KMUWqrw0',
    appId: '1:91810779138:ios:87c9674db186e404f8171b',
    messagingSenderId: '91810779138',
    projectId: 'running-loja',
    databaseURL: 'https://running-loja-default-rtdb.firebaseio.com',
    storageBucket: 'running-loja.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPv-InEyB1sBqS8YUGbIIXFy5KMUWqrw0',
    appId: '1:91810779138:ios:87c9674db186e404f8171b',
    messagingSenderId: '91810779138',
    projectId: 'running-loja',
    databaseURL: 'https://running-loja-default-rtdb.firebaseio.com',
    storageBucket: 'running-loja.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAOEAoRKBGPxImqxgdCwxu7JXKUkAkH8I',
    appId: '1:91810779138:web:3385e5a40227ed43f8171b',
    messagingSenderId: '91810779138',
    projectId: 'running-loja',
    authDomain: 'running-loja.firebaseapp.com',
    databaseURL: 'https://running-loja-default-rtdb.firebaseio.com',
    storageBucket: 'running-loja.firebasestorage.app',
  );
}
